config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get '/search' => 'spots#search'


  resources 'trips', only: [:index, :show, :edit, :update, :create, :destroy] do
    resources 'spots', only: [:show, :edit, :update, :new, :create, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
  end

resources 'lists', only: [:index, :edit, :update, :create, :destroy]

  get 'spots' => 'spots#index'

  resources :tags do
    get 'spots', to: 'spots#tag_search'
  end

  get 'trips_search' => 'trips#trips_search'
  get 'calendar' => 'trips#calendar'
  get 'favorite_all' => 'favorites#favorite_all'

  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'

end

app/models/spot.rb
class Spot < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :post_images, dependent: :destroy
  has_many :tagmaps, dependent: :destroy
  has_many :tags, through: :tagmaps
  accepts_attachments_for :post_images, attachment: :image, append: :true
  belongs_to :trip
  belongs_to :user

  # =============バリデーション=============
  validates :spot_name, presence: true
  validates :address, presence: true
  
  
  # =============GoogleMapに使用=============
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  
  # =============favolite=============
  def favorited_by?(user)
    favorites.where(user_id: user).exists?
  end

  # =============tag関連=============
  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_spot_tag = Tag.find_or_create_by(tag_name: new)
      self.tags << new_spot_tag
    end
  end

end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController

  def index
    gon.spots = Spot.where(user_id: current_user.id)
  end

  def show
    @spot = Spot.find(params[:id])
  end

  def new
    @spot = Spot.new
    @trip = Trip.find(params[:trip_id])
  end

  def create
    @trip = Trip.find(params[:trip_id])
    tag_list = params[:spot][:tag_name].split(/[[:blank:]]+/)
    @spot = @trip.spots.new(spot_params)
    @spot.user_id = current_user.id
    @spot.trip_id = @trip.id
    if @spot.save
      @spot.save_tag(tag_list)
      redirect_to trip_path(@trip.id)
    else
      render 'new'
    end
  end

  def edit
    @trip = Trip.find(params[:trip_id])
    @spot = Spot.find(params[:id])
  end

  def update
    @spot = Spot.find(params[:id])
    @trip = @spot.trip
    @spot.user_id = current_user.id
    if @spot.update(spot_params)
      if params[:spot][:image_ids]
        params[:spot][:image_ids].each do |image_id|
          image = @spot.post_images.find(image_id)
          image.delete
        end
      end
      redirect_to trip_spot_path(@spot.id)
    else
      render 'edit'
    end
  end

  def destroy
    spot = Spot.find(params[:id])
    spot.destroy
    redirect_to trip_path(params[:trip_id])
  end

  def search
    split_keyword = params[:keyword].split(/[[:blank:]]+/)
    @spots = []
    split_keyword.each do |keyword|
      next if keyword == ""
      @spots += Spot.where(["spot_name like? OR address like? OR comment like?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
    end
    @spots.uniq!
  end

  def tag_search
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @spots = @tag.spots.where(user_id: current_user.id)
  end

  private

  def spot_params
    params.require(:spot).permit(:user_id, :trip_id, :spot_name, :address, :comment, :latitude, :longitude, post_images_images: [])
  end

end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/_map.html.erb
<div id='map'></div>
<style>
#map{
    height: 500px;
    width: 1100px;
}
</style>

<script>

let map
let geocoder
let marker = [];
let infoWindow = [];
const spots = gon.spots;


function initMap(){
    geocoder = new google.maps.Geocoder()
    map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 35.681236, lng: 139.767125},
    zoom: 6
    });
    for (let i = 0; i < spots.length; i++) {
          marker[i] = new google.maps.Marker({
            position:{lat: spots[i].latitude, lng: spots[i].longitude},
            map: map
          });
          let id = spots[i]['id']
          infoWindow[i] = new google.maps.InfoWindow({
          content: `<a href='/trips/${spots[i].trip_id}/spots/${id}'>${spots[i].spot_name}</a>`
          });
          marker[i].addListener("click", function(){
              infoWindow[i].open(map, marker[i]);
          });
        };
}

</script>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY'] %>&callback=initMap" async defer></script>

app/views/spots/edit.html.erb
<div class="container text-center mt-2">
  <div class="text-left m-5 ">
    <%= link_to '<< 戻る', trip_spot_path(trip_id: @spot.trip, id: @spot) %>
  </div>

  <div class="mt-5 mb-5 p-5 col-md-8 col-12 border rounded mx-auto">
    <%= form_with(model:[@trip, @spot], local:true, url: "/trips/#{@trip.id}/spots/#{@spot.id}") do |f| %>

      <div class="field form-group">
        <h4>スポット名</h4>
        <%= f.text_field :spot_name, class: "form-control col-md-9 col-12 mx-auto" %>
      </div>

      <div class="field form-group">
      <h4>住所</h4>
      <%= f.text_field :address, class: "form-control col-md-9 col-12 mx-auto" %>
      </div>

      <div class="field form-group">
        <h4>comment</h4>
        <%= f.text_area :comment, class: "form-control col-md-9 col-12 mx-auto" %>
      </div>

      <div class="field form-group">
        <h4>画像</h4>

        <div class="detail_font m-2">
          shift + クリック　または　ctrl + クリックで</br>
          画像を選択し、アップロードしてください。
        </div>
        <div class="detail_font m-2 mx-auto col-md-8 col-12">
          <%= f.attachment_field :post_images_images, multiple: true, class: "form-control-file",onchange: "previewFiles()", id: "spot_post_images_images" %>
        </div>
        <!--------プレビュー-------->
        <div class="border rounded col-md-9 col-12 mx-auto p-5">
          <img src="" class="img-fluid" height="200" alt="preview..." name="preview0">
          <img src="" class="img-fluid" height="200" name="preview1">
          <img src="" class="img-fluid" height="200" name="preview2">
        </div>
        <!--------登録済み画像-------->
        <% if @spot.post_images.present? %>
          <div class="detail_font m-2">
            現在登録されている画像</br>
            （削除するものはチェックしてください）
          </div>
          <% @spot.post_images.each do |image| %>
          <%= f.check_box :image_ids, {multiple: true}, image.id, false %>
            <%= attachment_image_tag image, :image ,:fill, 200, 200 %> <br>
          <% end %>
        <% end %>

      </div>

      <div class="field form-group">
        <h4><%= f.label :tag_name, 'タグ付け' %></h4>
        <div class="detail_font mb-2">
          スペースを入力することで</br>
          複数のタグを付けることができます。
        </div>
        <%= f.text_field :tag_name, placeholder: "例：カフェ コロナ対策", class: "form-control col-md-9 col-12 mx-auto" %>
      </div>

      <%= f.submit '保存', class: "btn btn-outline-dark pl-5 pr-5" %>

    <% end %>
  </div>

  <div class="text-left m-5 ">
    <%= link_to '<< 戻る', trip_spot_path(trip_id: @spot.trip, id: @spot) %>
  </div>

</div>

app/views/spots/index.html.erb
<div class="container text-center mt-2">
  
  <div class='page_title'>Spot Map</div>
  <%= render 'spots/map', spots: @spots %>

</div>

app/views/spots/new.erb
<h1>spots#new</h1>

<%= form_with model:[@trip, @spot], local:true) do |f| %>

  <h4>スポット名</h4>
  <%= f.text_field :spot_name %>

  <h4>住所</h4>
  <%= f.text_field :address %>

  <h4>comment</h4>
  <%= f.text_area :comment %>

  <h4>画像</h4>
  <h7>
    shift + クリック　または　ctrl + クリックで画像を選択し、
    アップロードしてください。
  </h7><br>
  <!--プレビューの追加予定-->
  <%= f.attachment_field :post_images_images, multiple: true %>

  <%= f.submit '投稿' %>

<% end %>

app/views/spots/new.html.erb
    <%= link_to '<< 戻る', trip_path(@trip) %>
  </div>

  <div class="mt-5 mb-5 p-5 col-md-8 col-12 border rounded mx-auto">
    <% if @spot.errors.any? %>
    <div class="alert alert-warning">
      <ul>
        <% @spot.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>

  <% end %>
    <%= form_with(model: [@trip, @spot], local: true, method: :post, url: trip_spots_path ) do |f| %>

      <div class="field form-group">
        <h4>スポット名</h4>
        <%= f.text_field :spot_name, class: "form-control col-md-9 col-12 mx-auto" %>
      </div>

      <div class="field form-group">
      <h4>住所</h4>
      <%= f.text_field :address, class: "form-control col-md-9 col-12 mx-auto" %>
      </div>

      <div class="field form-group">
        <h4>comment</h4>
        <%= f.text_area :comment, class: "form-control col-md-9 col-12 mx-auto" %>
      </div>

      <div class="field form-group">
        <h4>画像</h4>

        <div class="detail_font m-2">
          shift + クリック　または　ctrl + クリックで</br>
          画像を選択し、アップロードしてください。
        </div>
        <div class="detail_font m-2 mx-auto col-md-8 col-12">
          <%= f.attachment_field :post_images_images, multiple: true, class: "form-control-file",onchange: "previewFiles()", id: "spot_post_images_images" %>
        </div>
        <!--------プレビュー-------->
        <div class="border rounded col-md-9 col-12 mx-auto p-5">
          <img src="" class="img-fluid" height="200" alt="preview..." name="preview0">
          <img src="" class="img-fluid" height="200" name="preview1">
          <img src="" class="img-fluid" height="200" name="preview2">
        </div>

      </div>

      <div class="field form-group">
        <h4><%= f.label :tag_name, 'タグ付け' %></h4>
        <div class="detail_font mb-2">
          スペースを入力することで</br>
          複数のタグを付けることができます。
        </div>
        <%= f.text_field :tag_name, placeholder: "例：カフェ コロナ対策", class: "form-control col-md-9 col-12 mx-auto" %>
      </div>

      <%= f.submit '投稿', class: "btn btn-outline-dark pl-5 pr-5" %>

    <% end %>
  </div>

  <div class="text-left m-5 ">
    <%= link_to '<< 戻る', trip_path(@trip) %>
  </div>
</div>

app/views/spots/search.html.erb
<div class="container text-center mt-2">
  <div class='page_title'>Spots検索</div>
  
  <% if @spots.length == 0 %>
    該当がありません
  <% else %>
    検索結果：<%= @spots.length %>件
  
    <% @spots.each do |spot| %>
      <div class='border rounded p-3 col-md-8 col-12 mx-auto m-2'>
        <div class="content_font">
          <%= link_to spot.spot_name, trip_spot_path(spot.trip.id, spot.id) %>
        </div>
        <div>
        <%= spot.address %>
        </div>
    
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval="10000">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <% spot.post_images.drop(1).count.times do |index| %>
            <li data-target="#carouselExampleIndicators" data-slide-to="#{index}"></li>
          <% end %>
        </ol>
    
          <div class="carousel-inner">
            <div class="carousel-item active">
              <% spot.post_images.first(1).each do |image| %>
                <%= attachment_image_tag image, :image, :fill, 500, 200, class: "carousel_image"  %>
              <% end %>
            </div>
            <% spot.post_images.drop(1).each do |image| %>
              <div class="carousel-item">
                <%= attachment_image_tag image, :image ,:fill, 500, 200, class: "carousel_image" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/spots/show.html.erb
<div class="container text-center mt-2">
  <div class="row">
    <div class="col-md-8 col-12 mx-auto border rounded p-3 mt-5">
      <div class="row">
        <div class="text-left col-6 pl-5">
          <%= render 'favorites/favorite_button', spot: @spot %>
        </div>
        <div class="text-right col-6">
          <%= link_to "削除", trip_spot_path(@spot.trip, @spot), method: :delete, "data-confirm" => "本当に削除しますか？" %>
          <%= link_to "編集",edit_trip_spot_path(@spot.trip, @spot) %>
        </div>
      </div>
  
      <div class='page_title'><%= @spot.spot_name %></div>
  
  
      <div class="content_font mb-3">
        <%= @spot.address %>
      </div>
      <div class="content_font mb-3">
        <%= @spot.comment %>
      </div>
      <div class="content_font">
        <% @spot.post_images.each do |image| %>
          <%= attachment_image_tag image, :image ,:fill, 200, 200 %>
        <% end %>
      </div>
      <% @spot.tags.each do |tag| %>
        <%= link_to tag.tag_name, tag_spots_path(tag_id: tag.id), class: "btn btn-dark btn-sm mt-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/spots/tag_search.html.erb
<div class="container text-center mt-2">
  <div class='title-font mt-5 mb-5'>[ <%= "#{@tag.tag_name}" %> ]の投稿一覧</div>


  <% @spots.each do |spot| %>
    <div class='border rounded p-3 col-md-8 col-12 mx-auto m-2'>
      <div class="content_font">
        <%= link_to spot.spot_name, trip_spot_path(spot.trip_id, spot.id) %>
      </div>
      <div>
      <%= spot.address %>
      </div>
    <!--------画像カルーセル表示-------->
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval="10000">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <% spot.post_images.drop(1).count.times do |index| %>
          <li data-target="#carouselExampleIndicators" data-slide-to="#{index}"></li>
        <% end %>
      </ol>
  
        <div class="carousel-inner">
          <div class="carousel-item active">
            <% spot.post_images.first(1).each do |image| %>
              <%= attachment_image_tag image, :image, :fill, 500, 200, class: "carousel_image"  %>
            <% end %>
          </div>
          <% spot.post_images.drop(1).each do |image| %>
            <div class="carousel-item">
              <%= attachment_image_tag image, :image ,:fill, 500, 200, class: "carousel_image" %>
            </div>
          <% end %>
        </div>
  
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </a>
      </div>
    </div>
  <% end %>
</div>