config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get '/search' => 'spots#search'


  resources 'trips', only: [:index, :show, :edit, :update, :create, :destroy] do
    resources 'spots', only: [:show, :edit, :update, :new, :create, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
  end

resources 'lists', only: [:index, :edit, :update, :create, :destroy]

  get 'spots' => 'spots#index'

  resources :tags do
    get 'spots', to: 'spots#tag_search'
  end

  get 'trips_search' => 'trips#trips_search'
  get 'calendar' => 'trips#calendar'
  get 'favorite_all' => 'favorites#favorite_all'

  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'

end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :spots, dependent: :destroy
  belongs_to :user

# =============バリデーション=============
  validates :starts_at, presence: true
  validates :ends_at, presence: true

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  def index
    @trips = Trip.where(user_id: current_user.id).order(id: "DESC")
    @trip = Trip.new
  end

  def show
    @trip = Trip.find(params[:id])
    @spots = @trip.spots.all
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.user_id = current_user.id
    if @trip.save
      redirect_to trip_path(@trip.id)
    else
      @trips = Trip.where(user_id: current_user.id).order(id: "DESC")
      @trip = Trip.new
      render 'index'
    end
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    trip = Trip.find(params[:id])
    trip.update(trip_params)
    redirect_to trip_path(trip.id)
  end

  def destroy
    trip = Trip.find(params[:id])
    trip.destroy
    redirect_to trips_path
  end

  def trips_search
    split_keyword = params[:keyword].split(/[[:blank:]]+/)
    @trips = []
    split_keyword.each do |keyword|
      next if keyword == ""
      @trips += Trip.where(["location like? OR comment like? ", "%#{keyword}%", "%#{keyword}%"])
    end
    @trips.uniq!
    @trip = Trip.new
    render 'index'
  end

  def calendar
    @trips = Trip.all
  end

  private

  def trip_params
    params.require(:trip).permit(:user_id, :location, :period, :comment, :starts_at, :ends_at)
  end

end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_new.html.erb
<%= form_with model:trip, local:true do |f| %>

  <div class="field form-group">
    <h4>旅行先</h4>
    <%= f.text_field :location, class: "form-control col-md-6 col-12 mx-auto" %>
  </div>

  <div class="field form-group">
    <h4>期間</h4>
    <span><%= f.datetime_field :starts_at, placeholder: "XXXX-XX-XX"%> ~ </span>
    <span><%= f.datetime_field :ends_at, placeholder: "XXXX-XX-XX"%></span><br>
  </div>

  <div class="field form-group">
    <h4>Comment</h4>
    <%= f.text_area :comment, class: "form-control col-md-6 col-12 mx-auto" %>
  </div>

  <%= f.submit '投稿', class: "btn btn-outline-dark pl-5 pr-5 mb-5" %>

<% end %>

app/views/trips/calendar.html.erb
<div class='page_title'>Calendar</div>

<div class="col-8 mx-auto" id="calendar"></div>

app/views/trips/edit.html.erb
  <div class="row">
    <div class="border rounded mx-auto p-5 col-md-6 col-12 mt-5 ">
    
    <%= form_with model:@trip, local:true do |f| %>
    
      <div class="field form-group">
        <h4>旅行先</h4>
        <%= f.text_field :location, class: "form-control col-12 mx-auto" %>
      </div>
        
      <div class="field form-group">
        <h4>期間</h4>
        <span><%= f.datetime_field :starts_at, placeholder: "XXXX-XX-XX", class: "form-control" %> ~ </span>
        <span><%= f.datetime_field :ends_at, placeholder: "XXXX-XX-XX", class: "form-control" %></span><br>
      </div>
      
      <div class="field form-group">
        <h4>comment</h4>
        <%= f.text_area :comment, class: "form-control col-12 mx-auto" %>
      </div>
    
      <%= f.submit '保存', class: "btn btn-outline-dark pl-5 pr-5 mb-5" %>
    
    <% end %>

  </div>
</div>

app/views/trips/index.erb
<h1>trips#index</h1>

<% @trips.each do |trip| %>
  <ul>
    <li>
      <%= link_to trip_path(trip.id) do %>
        <%= trip.location %>
      <% end %>
      <%= trip.period %>
      <%= trip.comment %>
    </li>
  </ul>
<% end %>

app/views/trips/index.html.erb
<div class='page_title'>Trips</div>
<!--------trip検索-------->
<div class="form-inline">
  <div class="form-group mx-auto m-2">
    <%= form_with url: trips_search_path, method: :get, class: 'mx-auto', local: true do |f| %>
      <%= f.text_field :keyword, value: @keyword, placeholder: "ワードを入力して検索", class: "form-control" %>
      <button type="submit" class="ml-2 btn btn-outline-dark">
        <i class="fas fa-search" aria-hidden="true"></i>
      </button>
    <% end %>
  </div>
</div>
<!--------trip投稿-------->
<div class="content">
  <a class="js-modal-open btn btn-outline-primary" href="">Tripを投稿</a>
</div>
<div class="modal js-modal">
    <div class="modal__bg js-modal-close"></div>
    <div class="modal__content">
        <%= render 'trips/new', trip: @trip %>
        <a class="js-modal-close" href="">閉じる</a>
    </div>
</div>
<!--------一覧表示-------->
<% if @trips.length == 0 %>
  <div class="border rounded-pill p-5 col-md-6 col-12 mx-auto mt-2">
    該当がありません
  </div>
<% end %>

<% @trips.each do |trip| %>
  <div class="border rounded-pill p-3 col-md-6 col-12 mx-auto m-2">
    <div class="content_font">
      <%= link_to trip_path(trip.id) do %>
        <%= trip.location %>
      <% end %>
    </div>
    <div class="detail_font">
      <%= trip.starts_at.strftime('%Y/%m/%d') %> ～ <%= trip.ends_at.strftime('%Y/%m/%d') %>
    </div>
  </div>
<% end %>

app/views/trips/mypage.html.erb
<div class="col-8" id="calendar"></div>

app/views/trips/new.erb
<h1>trips#new</h1>

<%= form_with model:@trip, local:true do |f| %>

  <h4>旅行先</h4>
  <%= f.text_field :location %>

  <h4>期間</h4>
  <%= f.text_field :period %>

  <h4>comment</h4>
  <%= f.text_area :comment %>

  <%= f.submit '投稿' %>

<% end %>

app/views/trips/show.html.erb
<div class="text-right">
  <%= link_to '削除', trip_path(@trip), method: :delete, "data-confirm" => "本当に削除しますか？" %>
  <%= link_to "編集する",edit_trip_path(@trip) %>
</div>
<div class="mx-auto col-md-8 col-12">
  <div class="title-font">
    <%= @trip.location %>
  </div>
  <div class="detail_font border rounded m-3 p-3">
  <li><%= @trip.starts_at.strftime('%Y/%m/%d') %> ～ <%= @trip.ends_at.strftime('%Y/%m/%d') %></li>
  <li><%= @trip.comment %></li>
  </div>
</div>

<div class='mb-3'>
  <%= link_to 'spot投稿', new_trip_spot_path(@trip.id), class: 'btn btn-outline-primary' %>
</div>

<% @spots.each do |spot| %>
  <div class='border rounded p-3 col-md-8 col-12 mx-auto m-2'>
    <div class="content_font">
      <%= link_to spot.spot_name, trip_spot_path(@trip.id, spot.id) %>
    </div>
    <div>
    <%= spot.address %>
    </div>
    <div class="text-left col-6 pl-5">
      <%= render 'favorites/favorite_button', spot: spot %>
    </div>

  <!--------画像カルーセル表示-------->
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval="10000">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <% spot.post_images.drop(1).count.times do |index| %>
        <li data-target="#carouselExampleIndicators" data-slide-to="#{index}"></li>
      <% end %>
    </ol>

      <div class="carousel-inner">
        <div class="carousel-item active">
          <% spot.post_images.first(1).each do |image| %>
            <%= attachment_image_tag image, :image, :fill, 500, 200, class: "carousel_image"  %>
          <% end %>
        </div>
        <% spot.post_images.drop(1).each do |image| %>
          <div class="carousel-item">
            <%= attachment_image_tag image, :image ,:fill, 500, 200, class: "carousel_image" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>