config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get '/search' => 'spots#search'


  resources 'trips', only: [:index, :show, :edit, :update, :create, :destroy] do
    resources 'spots', only: [:show, :edit, :update, :new, :create, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
  end

resources 'lists', only: [:index, :edit, :update, :create, :destroy]

  get 'spots' => 'spots#index'

  resources :tags do
    get 'spots', to: 'spots#tag_search'
  end

  get 'trips_search' => 'trips#trips_search'
  get 'calendar' => 'trips#calendar'
  get 'favorite_all' => 'favorites#favorite_all'

  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @tag_list = Tag.all
    if user_signed_in?
      @favorites = Favorite.all.where(user_id: current_user.id).order(id: "DESC")
    end
  end

  def guest_sign_in
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/top.erb
<h1>top</h1>

app/views/homes/top.html.erb
<div class='page_title text-center'>TripRecord</div>

<!--------menu-------->
<% if user_signed_in? %>
  <div class="row">
    <div class="menu_ber p-5 col-md-6 col-12 mb-5 text-center">
      <div class="content-title">Menu</div>
      <li class="menu">
        <%= link_to calendar_path, class:"menu-font" do %>
          <i class="far fa-calendar-alt"></i>
          Calendar
        <% end %>
      </li>
      <li class="menu">
        <%= link_to trips_path, class:"menu-font", data: {"turbolinks" => false} do %>
          <i class="fas fa-plane"></i>
          Trips
        <% end %>
      </li>
      <li class="menu">
        <%= link_to spots_path, class:"menu-font" do %>
          <i class="fas fa-map-marked-alt"></i>
          SpotsMap
        <% end %>
      </li>
      <li class="menu">
        <%= link_to lists_path, class:"menu-font", data: {"turbolinks" => false} do %>
          <i class="fas fa-external-link-alt"></i>
          NextPlan
        <% end %>
      </li>
      <li class="menu">
        <%= link_to destroy_user_session_path, method: :delete, class:"menu-font" do %>
          <i class="fas fa-sign-out-alt"></i>
          Log out
        <% end %>
      </li>
    </div>

    <div class="col-md-6 col-12 text-center">
<!--------検索-------->
      <div class="border rounded p-3">
      <div class="content-title">Spot検索</div>
        <div class="form-inline">
          <div class="form-group mx-auto m-2">
            <%= form_with url: search_path, method: :get, class: 'm-3', local: true do |f| %>
              <%= f.text_field :keyword, value: @keyword, placeholder: "ワードを入力して検索", class: "form-control" %>
              <button type="submit" class="btn btn-outline-dark ml-2">
                <i class="fas fa-search" aria-hidden="true"></i>
              </button>
            <% end %>
          </div>
        </div>
      </div>
<!--------favorite-------->
      <div class="border rounded p-3">
        <div class="content-title">お気に入り</div>
        <% if @favorites.count ==  0 %>
          <div class="col-12 mb-5">
              <h6 class="mx-auto m-3 p-5 border">まだお気に入りのスポットが登録されていません。</h6>
          </div>
        <% else %>
          <% @favorites.first(3).each do |favorite| %>
            <div class="text-center p-3">
              <%= link_to favorite.spot.spot_name, trip_spot_path(trip_id: favorite.spot.trip, id: favorite.spot) %>
            </div>
          <% end %>
          <div class="text-right mr-5">
            <%= link_to 'more >>', favorite_all_path %>
          </div>
        <% end %>
      </div>
<!--------Tag一覧-------->
      <div class="border rounded p-3 mb-5">
        <div class="content-title">Tag一覧</div>
          <div class="mt-3 mb-5">
            <% @tag_list.each do |list| %>
              <%= link_to list.tag_name, tag_spots_path(tag_id: list.id), class: "btn btn-outline-dark btn-sm" %>
            <% end %>
          </div>
      </div>

    </div>
  </div>

<% else %>
  <div class="m-5">
<!--------ログイン前-------->
    <div class="m-5">
      旅行の記録、写真をTripRecordで管理しよう！
    </div>

    <span>
      <%= link_to new_user_registration_path, class:"btn btn-outline-dark" do %>
        <i class="fas fa-user-plus"></i>
        新規登録
      <% end %>
    </span>

    <span>
      <%= link_to new_user_session_path, class:"btn btn-outline-dark" do %>
        <i class="fas fa-sign-in-alt"></i>
        ログイン
      <% end %>
    </span>

    <div class="m-3">
      <%= link_to 'ゲストログイン（閲覧用）', homes_guest_sign_in_path, method: :post, class: "btn btn-outline-dark" %>
    </div>
  </div>
<% end %>