config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get '/search' => 'spots#search'


  resources 'trips', only: [:index, :show, :edit, :update, :create, :destroy] do
    resources 'spots', only: [:show, :edit, :update, :new, :create, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
  end

resources 'lists', only: [:index, :edit, :update, :create, :destroy]

  get 'spots' => 'spots#index'

  resources :tags do
    get 'spots', to: 'spots#tag_search'
  end

  get 'trips_search' => 'trips#trips_search'
  get 'calendar' => 'trips#calendar'
  get 'favorite_all' => 'favorites#favorite_all'

  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'

end

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-center">
    © Trip_Record
    <%= link_to "https://github.com/kubotaseiko/Trip_record" do %>
      <i class="fab fa-github"></i>
    <% end %>
  </div>
</footer>

app/views/layouts/_header.erb
   <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to 'TripRecord', root_path, class:"navbar-brand" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <i class="fas fa-home"></i>
                <%= link_to new_trip_path, class:"nav-link text-light" do %>
                  NewTrip
                <% end %>
              </li>
              <li class="nav-item">
                <i class="fas fa-users"></i>
                
                  Spots
                
              </li>
              <li class="nav-item">
                <%= link_to trips_path, class:"nav-link text-light" do %>
                  <i class="fas fa-book-open"></i>
                  trips
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do %>
                  <i class="fas fa-sign-out-alt"></i>
                  logout
                <% end %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to root_path, class:"nav-link text-light" do %>
                <i class="fas fa-home"></i>
                Home
                <% end %>
              </li>
              <li class="nav-item">
                <i class="fas fa-link"></i>
                About
              </li>
              <li class="nav-item">
                <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
                <i class="fas fa-user-plus"></i>
                sign up
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_session_path, class:"nav-link text-light" do %>
                <i class="fas fa-sign-in-alt"></i>
                login
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

app/views/layouts/_header.html.erb
   <header>
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <h2><%= link_to 'TripRecord', root_path, class:"navbar-brand" %></h2>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to calendar_path,class:"nav-link text-light" do %>
                  <i class="far fa-calendar-alt d-none d-lg-block fa-2x"></i>
                  <div class="d-md-block d-lg-none"><i class="far fa-calendar-alt"></i>&emsp;Carendar</div>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to spots_path, class:"nav-link text-light" do %>
                  <i class="fas fa-map-marked-alt d-none d-lg-block fa-2x"></i>
                  <div class="d-md-block d-lg-none"><i class="fas fa-map-marked-alt"></i>&emsp;Map</div>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to trips_path, class:"nav-link text-light", data: {"turbolinks" => false} do %>
                  <i class="fas fa-plane d-none d-lg-block fa-2x"></i>
                  <div class="d-md-block d-lg-none"><i class="fas fa-plane"></i>&emsp;Trip</div>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to lists_path, class:"nav-link text-light", data: {"turbolinks" => false} do %>
                  <i class="fas fa-external-link-alt d-none d-lg-block fa-2x"></i>
                  <div class="d-md-block d-lg-none"><i class="fas fa-external-link-alt"></i>&emsp;Next Plan</div>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do %>
                  <i class="fas fa-sign-out-alt d-none d-lg-block fa-2x"></i>
                  <div class="d-md-block d-lg-none"><i class="fas fa-sign-out-alt"></i>&emsp;ログアウト</div>
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TripRecord</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/4c89741d8a.js" crossorigin="anonymous"></script>
    <%= include_gon %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=DotGothic16&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <div class="footerFixed"><!--画面下部にfooter配置-->
      <%= render "layouts/header" %>
      <header></header>
        <div class="container text-center mt-2">
          <%= yield %>
        </div>
      <%= render "layouts/footer" %>
    </div>

  </body>
</html>